
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-01-26T10:27:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e8df32f8dc80711a012b061c50ea35a14c45e2c",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
